apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/manjulachukki/shopNow'
    targetRevision: HEAD
    path: kubernetes/helm/charts/admin
    helm:
      valueFiles: []
      releaseName: admin
      parameters:
      - name: image.repository
        value: 975050024946.dkr.ecr.us-east-1.amazonaws.com/manjula-shopnow-admin
      - name: image.tag
        value: latest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shopnow-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
